#!/usr/bin/env python3
"""
Generate comprehensive definitions for all vocabulary words.
Fills in the placeholder definitions with real content.
Also generates proper double-take quiz sentences and secret passages.
"""

import json
import os
import random

random.seed(42)

# ============================================================
# COMPREHENSIVE DEFINITIONS DATABASE
# Each entry: word -> {pos, m1, m2, challenge, synonyms, antonyms}
# ============================================================

DEFS = {
    # --- A ---
    "abandon": {"pos": "verb", "m1": "To leave behind completely and not return. Example: The sailors had to abandon the sinking ship.", "m2": "Wild, uncontrolled behavior. Example: The children danced with wild abandon.", "ch": "The family had to ___ their home during the flood."},
    "ability": {"pos": "noun", "m1": "The power or skill to do something. Example: She has the ability to solve difficult math problems.", "m2": "", "ch": "His ___ to play the piano amazed everyone."},
    "abolish": {"pos": "verb", "m1": "To officially end or stop something, especially a law or system. Example: Abraham Lincoln helped abolish slavery.", "m2": "", "ch": "The school voted to ___ the old dress code."},
    "absorb": {"pos": "verb", "m1": "To soak up or take in. Example: The sponge will absorb the water.", "m2": "To be very interested in something. Example: She was absorbed in her book.", "ch": "The towel can ___ a lot of water."},
    "abuse": {"pos": "noun, verb", "m1": "To treat something or someone badly or cruelly. Example: We should never abuse animals.", "m2": "Wrong or harmful use. Example: The abuse of power is dangerous.", "ch": "It is wrong to ___ someone's trust."},
    "accelerate": {"pos": "verb", "m1": "To increase speed or make something happen faster. Example: The car began to accelerate on the highway.", "m2": "", "ch": "The runner started to ___ as she neared the finish line."},
    "access": {"pos": "noun, verb", "m1": "The ability or right to enter or use something. Example: Students have access to the library.", "m2": "", "ch": "The password gives you ___ to the website."},
    "accident": {"pos": "noun", "m1": "Something bad that happens without being planned. Example: The car accident blocked the road.", "m2": "Something that happens by chance. Example: I found the book by accident.", "ch": "The ___ happened because the road was icy."},
    "accomplish": {"pos": "verb", "m1": "To successfully finish or achieve something. Example: She accomplished her goal of reading 50 books.", "m2": "", "ch": "What do you want to ___ this year?"},
    "accurate": {"pos": "adjective", "m1": "Correct and free from mistakes. Example: The weather forecast was accurate.", "m2": "", "ch": "Make sure your answer is ___ before turning in the test."},
    "accuse": {"pos": "verb", "m1": "To say that someone has done something wrong. Example: They accused him of cheating on the test.", "m2": "", "ch": "Don't ___ someone without proof."},
    "achieve": {"pos": "verb", "m1": "To succeed in doing something after trying hard. Example: She worked hard to achieve her dream.", "m2": "", "ch": "You can ___ anything if you keep trying."},
    "achievement": {"pos": "noun", "m1": "Something important that is done successfully. Example: Landing on the moon was a great achievement.", "m2": "", "ch": "Winning the spelling bee was her greatest ___."},
    "acknowledge": {"pos": "verb", "m1": "To accept or admit that something is true. Example: He acknowledged his mistake and apologized.", "m2": "", "ch": "The teacher asked her to ___ the rules."},
    "acquire": {"pos": "verb", "m1": "To get or gain something over time. Example: She acquired new skills during the summer program.", "m2": "", "ch": "You can ___ knowledge by reading every day."},
    "active": {"pos": "adjective", "m1": "Always doing things; full of energy. Example: Dogs need to be active and play every day.", "m2": "", "ch": "Staying ___ helps you stay healthy."},
    "actual": {"pos": "adjective", "m1": "Real and true, not imagined. Example: The actual cost was higher than we expected.", "m2": "", "ch": "The ___ distance is longer than it looks on the map."},
    "adapt": {"pos": "verb", "m1": "To change in order to fit a new situation. Example: Animals adapt to survive in different climates.", "m2": "", "ch": "You need to ___ to a new school quickly."},
    "adequate": {"pos": "adjective", "m1": "Enough; sufficient for what is needed. Example: Is there adequate food for everyone?", "m2": "", "ch": "We need ___ sleep to do well in school."},
    "adhesive": {"pos": "noun, adjective", "m1": "A substance like glue that sticks things together. Example: Use adhesive tape to seal the box.", "m2": "", "ch": "The ___ on the envelope was not strong enough."},
    "admire": {"pos": "verb", "m1": "To look at something with pleasure or to respect someone. Example: I admire my teacher for her patience.", "m2": "", "ch": "Everyone ___ the beautiful sunset."},
    "adopt": {"pos": "verb", "m1": "To take in and raise as your own. Example: They decided to adopt a rescue dog.", "m2": "To start using a new idea or method. Example: The school adopted a new reading program.", "ch": "Our family wants to ___ a kitten from the shelter."},
    "advantage": {"pos": "noun", "m1": "Something that helps you do better than others. Example: Being tall is an advantage in basketball.", "m2": "", "ch": "Speaking two languages is a big ___."},
    "adventure": {"pos": "noun", "m1": "An exciting or unusual experience. Example: Camping in the mountains was a great adventure.", "m2": "", "ch": "The book was about a pirate's ___ on the high seas."},
    "advice": {"pos": "noun", "m1": "Suggestions about what someone should do. Example: My grandmother always gives good advice.", "m2": "", "ch": "What ___ would you give to a new student?"},
    "aggressive": {"pos": "adjective", "m1": "Ready to attack or behave in a forceful way. Example: The aggressive dog growled at strangers.", "m2": "", "ch": "The player was too ___ during the game."},
    "aim": {"pos": "verb, noun", "m1": "To point or direct toward a target. Example: She aimed the ball at the basket.", "m2": "A goal or purpose. Example: His aim is to become a doctor.", "ch": "Her ___ was to finish the race."},
    "alert": {"pos": "adjective, verb", "m1": "Paying careful attention; watchful. Example: The guard remained alert all night.", "m2": "To warn someone. Example: The alarm alerted everyone to the fire.", "ch": "Stay ___ when crossing the street."},
    "allow": {"pos": "verb", "m1": "To let someone do something; to permit. Example: The teacher allowed extra time for the test.", "m2": "", "ch": "My parents ___ me to stay up late on weekends."},
    "alter": {"pos": "verb", "m1": "To change something, usually slightly. Example: She altered her dress to make it shorter.", "m2": "", "ch": "They had to ___ their plans because of the rain."},
    "altitude": {"pos": "noun", "m1": "The height of something above sea level. Example: The plane flew at a high altitude.", "m2": "", "ch": "Mountain climbers must adjust to high ___."},
    "amateur": {"pos": "noun, adjective", "m1": "Someone who does something for fun, not as a job. Example: He is an amateur photographer.", "m2": "", "ch": "The ___ painter was surprisingly talented."},
    "ambition": {"pos": "noun", "m1": "A strong desire to achieve something. Example: Her ambition is to become an astronaut.", "m2": "", "ch": "With hard work and ___, you can achieve your goals."},
    "ample": {"pos": "adjective", "m1": "More than enough; plenty. Example: There was ample food for everyone at the party.", "m2": "", "ch": "We had ___ time to finish the test."},
    "analyze": {"pos": "verb", "m1": "To examine something carefully to understand it. Example: Scientists analyze data from experiments.", "m2": "", "ch": "The detective had to ___ the clues carefully."},
    "ancestor": {"pos": "noun", "m1": "A person in your family who lived a long time ago. Example: My ancestors came from India.", "m2": "", "ch": "We learned about our ___ through old family photos."},
    "ancient": {"pos": "adjective", "m1": "Very, very old; from a time long ago. Example: The ancient ruins were thousands of years old.", "m2": "", "ch": "The museum had ___ artifacts from Egypt."},
    "anchor": {"pos": "noun, verb", "m1": "A heavy object dropped into water to keep a boat in place. Example: The captain dropped the anchor near the shore.", "m2": "A person who reads the news on TV. Example: She works as a news anchor.", "ch": "The ship dropped its ___ in the harbor."},
    "announce": {"pos": "verb", "m1": "To say something officially or publicly. Example: The principal announced the winners of the contest.", "m2": "", "ch": "They will ___ the results tomorrow."},
    "anthem": {"pos": "noun", "m1": "An important song, especially one representing a country. Example: Everyone stood for the national anthem.", "m2": "", "ch": "The crowd sang the ___ before the game."},
    "anxious": {"pos": "adjective", "m1": "Feeling worried or nervous about something. Example: She felt anxious before the big test.", "m2": "", "ch": "He was ___ about his first day at a new school."},
    "apparent": {"pos": "adjective", "m1": "Easy to see or understand; obvious. Example: It was apparent that she had practiced hard.", "m2": "", "ch": "The answer was ___ once she read the question again."},
    "appeal": {"pos": "verb, noun", "m1": "To ask for something urgently. Example: The charity made an appeal for donations.", "m2": "To be attractive or interesting. Example: The colorful cover appealed to young readers.", "ch": "The teacher made an ___ for students to join the club."},
    "appear": {"pos": "verb", "m1": "To come into sight or become visible. Example: Stars appear in the sky at night.", "m2": "To seem. Example: She appeared tired after the long trip.", "ch": "The rainbow will ___ after the rain stops."},
    "appreciate": {"pos": "verb", "m1": "To understand the value of something and be grateful for it. Example: I appreciate your help with my homework.", "m2": "", "ch": "We should ___ the kindness of others."},
    "approach": {"pos": "verb, noun", "m1": "To come near or closer to something. Example: We watched the train approach the station.", "m2": "A way of dealing with something. Example: She tried a different approach to the problem.", "ch": "As we ___ the castle, it looked bigger and bigger."},
    "appropriate": {"pos": "adjective", "m1": "Suitable or right for a particular situation. Example: Wearing a raincoat is appropriate on a rainy day.", "m2": "", "ch": "Make sure your behavior is ___ for the library."},
    "approve": {"pos": "verb", "m1": "To agree with or accept something. Example: The committee approved the new playground plan.", "m2": "", "ch": "Did your parents ___ of your choice?"},
    "approximate": {"pos": "adjective, verb", "m1": "Close to the actual amount but not exact. Example: The approximate distance is five miles.", "m2": "", "ch": "What is the ___ number of students in your school?"},
    "arctic": {"pos": "adjective, noun", "m1": "Relating to the very cold region around the North Pole. Example: Polar bears live in the arctic.", "m2": "", "ch": "The ___ winds made the temperature drop below zero."},
    "argue": {"pos": "verb", "m1": "To express a different opinion, sometimes angrily. Example: The siblings argued about which movie to watch.", "m2": "To give reasons for or against something. Example: She argued that recess should be longer.", "ch": "Don't ___ with your friend over something small."},
    "aroma": {"pos": "noun", "m1": "A pleasant smell, especially of food. Example: The aroma of fresh bread filled the kitchen.", "m2": "", "ch": "The ___ of the cookies baking made everyone hungry."},
    "arrange": {"pos": "verb", "m1": "To put things in order or to make plans. Example: She arranged the flowers in a vase.", "m2": "", "ch": "Please ___ the books on the shelf by size."},
    "atmosphere": {"pos": "noun", "m1": "The layer of gases surrounding the Earth. Example: The atmosphere protects us from harmful rays.", "m2": "The feeling or mood of a place. Example: The restaurant had a friendly atmosphere.", "ch": "The ___ in the room was tense before the announcement."},
    "attract": {"pos": "verb", "m1": "To pull toward or cause interest. Example: The bright flowers attract butterflies.", "m2": "", "ch": "The magnet will ___ the metal clips."},
    "auction": {"pos": "noun, verb", "m1": "A public sale where things go to the highest bidder. Example: The painting sold at auction for a million dollars.", "m2": "", "ch": "The rare coin was sold at an ___."},
    "available": {"pos": "adjective", "m1": "Ready to be used or obtained. Example: Is this seat available?", "m2": "", "ch": "The library book is now ___ for checkout."},
    "avoid": {"pos": "verb", "m1": "To stay away from someone or something. Example: She tried to avoid stepping in the puddle.", "m2": "", "ch": "You should ___ eating too much sugar."},
    "aware": {"pos": "adjective", "m1": "Knowing about something; conscious of it. Example: He was aware of the danger ahead.", "m2": "", "ch": "Are you ___ that the test is tomorrow?"},
    "awe": {"pos": "noun", "m1": "A feeling of wonder and amazement. Example: The Grand Canyon filled her with awe.", "m2": "", "ch": "The fireworks display left the crowd in ___."},
    "awkward": {"pos": "adjective", "m1": "Clumsy or uncomfortable. Example: There was an awkward silence after his joke.", "m2": "", "ch": "He felt ___ at the party where he didn't know anyone."},
    # Continue with B-Z...
    "bargain": {"pos": "noun, verb", "m1": "Something bought for less than the usual price. Example: She got a great bargain at the sale.", "m2": "An agreement between people. Example: They made a bargain to share the work.", "ch": "The shoes were a real ___ at half price."},
    "barrier": {"pos": "noun", "m1": "Something that blocks the way or prevents progress. Example: The fence was a barrier to the garden.", "m2": "Something that makes communication difficult. Example: Language can be a barrier between people.", "ch": "The river was a natural ___ between the two towns."},
    "bashful": {"pos": "adjective", "m1": "Shy and easily embarrassed. Example: The bashful child hid behind her mother.", "m2": "", "ch": "The ___ kitten hid under the bed when visitors came."},
    "bitter": {"pos": "adjective", "m1": "Having a sharp, unpleasant taste. Example: The medicine tasted bitter.", "m2": "Feeling angry or disappointed. Example: She was bitter about losing the competition.", "ch": "The ___ cold made everyone hurry inside."},
    "blizzard": {"pos": "noun", "m1": "A severe snowstorm with strong winds. Example: The blizzard dumped three feet of snow.", "m2": "", "ch": "Schools were closed because of the ___."},
    "blunder": {"pos": "noun, verb", "m1": "A stupid or careless mistake. Example: Forgetting the password was a terrible blunder.", "m2": "", "ch": "The goalkeeper's ___ cost the team the game."},
    "boast": {"pos": "verb", "m1": "To talk proudly about yourself. Example: He boasted about his high test score.", "m2": "", "ch": "Don't ___ about winning — be a good sport."},
    "bold": {"pos": "adjective", "m1": "Brave and confident; not afraid. Example: The bold explorer ventured into the cave.", "m2": "", "ch": "It was ___ of her to speak up in front of everyone."},
    "border": {"pos": "noun, verb", "m1": "The edge or boundary of something. Example: The river forms the border between the two countries.", "m2": "", "ch": "Flowers grew along the ___ of the garden."},
    "boycott": {"pos": "verb, noun", "m1": "To refuse to buy or use something as a protest. Example: People boycotted the company for polluting the river.", "m2": "", "ch": "The students organized a ___ of the unfair rule."},
    "brief": {"pos": "adjective", "m1": "Short in time or length. Example: The teacher gave a brief explanation of the rules.", "m2": "", "ch": "He made a ___ stop at the store."},
    "brilliant": {"pos": "adjective", "m1": "Very bright or shining. Example: The brilliant sun lit up the sky.", "m2": "Extremely smart or talented. Example: She is a brilliant scientist.", "ch": "The ___ idea solved the problem immediately."},
    "brink": {"pos": "noun", "m1": "The edge of something steep or dangerous. Example: They stood on the brink of the cliff.", "m2": "Very close to a new situation. Example: The team was on the brink of victory.", "ch": "The country was on the ___ of a great discovery."},
    "burden": {"pos": "noun, verb", "m1": "Something heavy that is carried; a heavy responsibility. Example: The heavy backpack was a burden to carry.", "m2": "", "ch": "She didn't want to be a ___ to her family."},
    "campaign": {"pos": "noun, verb", "m1": "An organized effort to achieve a goal. Example: The campaign to clean up the park was successful.", "m2": "", "ch": "She ran a great ___ for class president."},
    "capable": {"pos": "adjective", "m1": "Having the ability or skill to do something. Example: She is capable of solving any math problem.", "m2": "", "ch": "With practice, you are ___ of great things."},
    "capture": {"pos": "verb, noun", "m1": "To catch or take control of someone or something. Example: The police captured the thief.", "m2": "To record or preserve. Example: The photographer captured a beautiful sunset.", "ch": "The explorer tried to ___ the butterfly without harming it."},
    "catastrophe": {"pos": "noun", "m1": "A sudden terrible disaster. Example: The earthquake was a catastrophe that destroyed many buildings.", "m2": "", "ch": "The oil spill was an environmental ___."},
    "cautious": {"pos": "adjective", "m1": "Being very careful to avoid danger or mistakes. Example: Be cautious when crossing the busy road.", "m2": "", "ch": "The ___ driver slowed down in the rain."},
    "cease": {"pos": "verb", "m1": "To stop or come to an end. Example: The rain ceased and the sun came out.", "m2": "", "ch": "The noise will ___ when the concert ends."},
    "certain": {"pos": "adjective", "m1": "Sure about something; having no doubt. Example: I am certain this is the right answer.", "m2": "", "ch": "She was ___ that she had locked the door."},
    "champion": {"pos": "noun", "m1": "A person who wins a competition. Example: She became the spelling bee champion.", "m2": "Someone who fights for a cause. Example: He was a champion of equal rights.", "ch": "The team celebrated their ___ player."},
    "chill": {"pos": "noun, verb", "m1": "A feeling of coldness. Example: A chill ran down her spine.", "m2": "To make something cold. Example: Chill the lemonade in the fridge.", "ch": "There was a ___ in the air that morning."},
    "clasp": {"pos": "verb, noun", "m1": "To hold tightly. Example: She clasped the necklace around her neck.", "m2": "A device that holds things together. Example: The clasp on the bracelet broke.", "ch": "He ___ the trophy tightly in his hands."},
    "clever": {"pos": "adjective", "m1": "Quick to learn and understand; smart. Example: The clever fox outsmarted the hunters.", "m2": "", "ch": "That was a ___ way to solve the puzzle."},
    "climate": {"pos": "noun", "m1": "The usual weather conditions in an area over a long time. Example: Tropical climates are warm and rainy.", "m2": "", "ch": "The ___ in the desert is hot and dry."},
    "cling": {"pos": "verb", "m1": "To hold on tightly to something. Example: The baby clung to her mother.", "m2": "", "ch": "The wet leaves ___ to the window."},
    "coast": {"pos": "noun, verb", "m1": "The land next to the sea. Example: We drove along the coast to see the ocean.", "m2": "To move without effort. Example: The bike coasted down the hill.", "ch": "Beautiful beaches line the ___ of California."},
    "colossal": {"pos": "adjective", "m1": "Extremely large; enormous. Example: The colossal statue could be seen from miles away.", "m2": "", "ch": "The dinosaur skeleton was ___ — it filled the whole room."},
    "common": {"pos": "adjective", "m1": "Happening often; usual. Example: Rain is common in April.", "m2": "Shared by everyone. Example: We have a common interest in music.", "ch": "Sparrows are ___ birds you can see anywhere."},
    "communicate": {"pos": "verb", "m1": "To share information or ideas with others. Example: We communicate through speech, writing, and gestures.", "m2": "", "ch": "It's important to ___ clearly with your teammates."},
    "companion": {"pos": "noun", "m1": "A person or animal you spend time with. Example: The dog was her loyal companion.", "m2": "", "ch": "A good book can be a wonderful ___ on a rainy day."},
    "compassion": {"pos": "noun", "m1": "Feeling sympathy for others and wanting to help them. Example: She showed compassion by helping the injured bird.", "m2": "", "ch": "The doctor treated her patients with great ___."},
    "compete": {"pos": "verb", "m1": "To try to win against others. Example: Six teams will compete in the tournament.", "m2": "", "ch": "The students ___ in the science fair every year."},
    "conceal": {"pos": "verb", "m1": "To hide something from sight or from others. Example: She concealed the gift behind her back.", "m2": "", "ch": "The spy tried to ___ the secret documents."},
    "conflict": {"pos": "noun, verb", "m1": "A serious disagreement or fight. Example: The conflict between the two countries lasted for years.", "m2": "", "ch": "The characters in the story had a ___ to resolve."},
    "conquer": {"pos": "verb", "m1": "To defeat or overcome something. Example: She conquered her fear of heights.", "m2": "", "ch": "The army tried to ___ the enemy's fortress."},
    "consequence": {"pos": "noun", "m1": "The result of something that happened. Example: One consequence of not studying is a low grade.", "m2": "", "ch": "Every choice has a ___."},
    "consider": {"pos": "verb", "m1": "To think about something carefully. Example: Consider all your options before deciding.", "m2": "", "ch": "Please ___ how your words affect others."},
    "continue": {"pos": "verb", "m1": "To keep doing something without stopping. Example: Please continue reading from where you left off.", "m2": "", "ch": "The rain will ___ throughout the day."},
    "contribute": {"pos": "verb", "m1": "To give something to help. Example: Everyone contributed food for the bake sale.", "m2": "", "ch": "You can ___ to the project by sharing your ideas."},
    "convince": {"pos": "verb", "m1": "To make someone believe or agree with something by giving good reasons. Example: She convinced her parents to let her go camping.", "m2": "", "ch": "How would you ___ your teacher to give less homework?"},
    "courage": {"pos": "noun", "m1": "The ability to face fear or danger bravely. Example: It takes courage to stand up for what is right.", "m2": "", "ch": "The firefighter showed great ___ during the rescue."},
    "coward": {"pos": "noun", "m1": "A person who is too afraid to do something. Example: He felt like a coward for not speaking up.", "m2": "", "ch": "Calling someone a ___ is very unkind."},
    "custom": {"pos": "noun", "m1": "A tradition or usual way of doing something. Example: It is a custom to shake hands when meeting someone.", "m2": "", "ch": "In many countries, removing shoes indoors is a ___."},
    "cycle": {"pos": "noun, verb", "m1": "A series of events that repeat in the same order. Example: The water cycle includes evaporation and rain.", "m2": "To ride a bicycle. Example: She cycles to school every day.", "ch": "Spring, summer, fall, winter — the ___ of seasons repeats."},
    "damage": {"pos": "noun, verb", "m1": "Harm or injury that makes something less useful. Example: The storm caused serious damage to the roof.", "m2": "", "ch": "The flood caused ___ to many homes."},
    "debate": {"pos": "noun, verb", "m1": "A formal discussion where people argue different sides. Example: The class held a debate about school uniforms.", "m2": "", "ch": "The candidates had a ___ before the election."},
    "decade": {"pos": "noun", "m1": "A period of ten years. Example: The building was constructed a decade ago.", "m2": "", "ch": "A lot can change in a ___."},
    "decay": {"pos": "verb, noun", "m1": "To slowly break down or rot. Example: Fallen leaves decay on the forest floor.", "m2": "", "ch": "Sugar can cause your teeth to ___."},
    "defeat": {"pos": "verb, noun", "m1": "To win against someone in a contest or battle. Example: Our team defeated the champions.", "m2": "", "ch": "They celebrated their ___ of the rival team."},
    "defend": {"pos": "verb", "m1": "To protect from attack or danger. Example: The knight defended the castle.", "m2": "", "ch": "A mother bear will ___ her cubs."},
    "defiant": {"pos": "adjective", "m1": "Boldly refusing to obey. Example: The defiant child crossed her arms and said no.", "m2": "", "ch": "The ___ look on her face showed she would not give in."},
    "delicate": {"pos": "adjective", "m1": "Easily broken or damaged; fragile. Example: Be careful with that delicate glass ornament.", "m2": "Fine and subtle in quality. Example: The painting had delicate brushstrokes.", "ch": "The butterfly's wings were so ___ they looked like paper."},
    "delightful": {"pos": "adjective", "m1": "Causing great pleasure and happiness. Example: The garden was a delightful place to read.", "m2": "", "ch": "The children had a ___ time at the fair."},
    "demonstrate": {"pos": "verb", "m1": "To show how something works or is done. Example: The teacher demonstrated the science experiment.", "m2": "", "ch": "Can you ___ how to fold a paper crane?"},
    "depart": {"pos": "verb", "m1": "To leave, especially to start a journey. Example: The train will depart at noon.", "m2": "", "ch": "We will ___ for the airport at six in the morning."},
    "depend": {"pos": "verb", "m1": "To rely on someone or something. Example: Young birds depend on their parents for food.", "m2": "", "ch": "You can ___ on me to help."},
    "describe": {"pos": "verb", "m1": "To tell what something or someone is like. Example: Can you describe your favorite place?", "m2": "", "ch": "___ the main character in the story."},
    "desperate": {"pos": "adjective", "m1": "Feeling hopeless or having a great need. Example: The lost hikers were desperate for water.", "m2": "", "ch": "The team made a ___ effort to score in the last minute."},
    "determine": {"pos": "verb", "m1": "To decide something firmly. Example: She was determined to finish the race.", "m2": "To find out or establish. Example: Scientists determined the age of the fossils.", "ch": "Hard work will ___ your success."},
    "diminutive": {"pos": "adjective", "m1": "Extremely small; tiny. Example: The diminutive kitten fit in the palm of her hand.", "m2": "", "ch": "The ___ flowers grew between the cracks in the sidewalk."},
    "discover": {"pos": "verb", "m1": "To find something for the first time. Example: Scientists discovered a new species of frog.", "m2": "", "ch": "The children ___ a hidden cave in the hillside."},
    "disguise": {"pos": "noun, verb", "m1": "Something that changes your appearance to hide who you are. Example: The spy wore a disguise to blend in.", "m2": "", "ch": "The superhero wore a ___ so nobody would recognize her."},
    "display": {"pos": "verb, noun", "m1": "To show something publicly. Example: The museum displayed the ancient pottery.", "m2": "", "ch": "The store window had a beautiful ___ of flowers."},
    "distinct": {"pos": "adjective", "m1": "Clearly different from others. Example: Each snowflake has a distinct pattern.", "m2": "", "ch": "The two flavors were quite ___ from each other."},
    "distinguish": {"pos": "verb", "m1": "To recognize the difference between things. Example: Can you distinguish between the twin sisters?", "m2": "", "ch": "It was hard to ___ the fake jewel from the real one."},
    "disturb": {"pos": "verb", "m1": "To interrupt or bother someone. Example: Please don't disturb me while I'm studying.", "m2": "", "ch": "The loud noise will ___ the sleeping baby."},
    "diverse": {"pos": "adjective", "m1": "Showing a great deal of variety. Example: Our school has a diverse group of students from many countries.", "m2": "", "ch": "The rainforest has ___ plant and animal life."},
    "dominate": {"pos": "verb", "m1": "To have power over or be the most important. Example: The tall building dominated the skyline.", "m2": "", "ch": "The team ___ the game from start to finish."},
    "drift": {"pos": "verb, noun", "m1": "To be carried along slowly by water or air. Example: The boat drifted down the river.", "m2": "", "ch": "Clouds ___ slowly across the sky."},
    "drought": {"pos": "noun", "m1": "A long period of time with very little rain. Example: The drought caused the crops to die.", "m2": "", "ch": "The ___ lasted for three months and the rivers dried up."},
    "drowsy": {"pos": "adjective", "m1": "Feeling sleepy. Example: The warm sun made her feel drowsy.", "m2": "", "ch": "The ___ student could barely keep his eyes open."},
    "eager": {"pos": "adjective", "m1": "Very excited and wanting to do something. Example: The eager students raised their hands.", "m2": "", "ch": "She was ___ to start her first day of camp."},
    "eloquent": {"pos": "adjective", "m1": "Speaking in a powerful and beautiful way. Example: The president gave an eloquent speech.", "m2": "", "ch": "Her ___ words moved the audience to tears."},
    "emphasize": {"pos": "verb", "m1": "To give special importance to something. Example: The teacher emphasized the importance of reading.", "m2": "", "ch": "I want to ___ how important this rule is."},
    "encounter": {"pos": "verb, noun", "m1": "To meet or experience something unexpectedly. Example: We encountered a deer on the hiking trail.", "m2": "", "ch": "She did not expect to ___ her old friend at the store."},
    "encourage": {"pos": "verb", "m1": "To give support or confidence to someone. Example: The coach encouraged the team to keep trying.", "m2": "", "ch": "Parents should ___ their children to read."},
    "endure": {"pos": "verb", "m1": "To suffer through something difficult without giving up. Example: The runners endured the heat to finish the marathon.", "m2": "", "ch": "She had to ___ the long wait at the doctor's office."},
    "enormous": {"pos": "adjective", "m1": "Extremely large. Example: The enormous whale swam past the boat.", "m2": "", "ch": "The ___ pizza was big enough for the whole class."},
    "environment": {"pos": "noun", "m1": "The natural world around us. Example: We must protect the environment from pollution.", "m2": "The surroundings or conditions you live in. Example: A quiet environment helps you study.", "ch": "Planting trees helps the ___."},
    "escalate": {"pos": "verb", "m1": "To increase or become more serious. Example: The argument began to escalate quickly.", "m2": "", "ch": "The small problem could ___ into a big one."},
    "establish": {"pos": "verb", "m1": "To set up or create something. Example: They established a new school in the village.", "m2": "", "ch": "The company was ___ in 1985."},
    "evaluate": {"pos": "verb", "m1": "To judge or determine the value or quality of something. Example: The teacher evaluated each student's work.", "m2": "", "ch": "Take time to ___ all your options."},
    "evident": {"pos": "adjective", "m1": "Easily seen or understood; obvious. Example: It was evident that she had been crying.", "m2": "", "ch": "The damage from the storm was ___."},
    "exaggerate": {"pos": "verb", "m1": "To make something seem bigger or more important than it really is. Example: He exaggerated when he said the fish was five feet long.", "m2": "", "ch": "Don't ___ — tell the truth about what happened."},
    "examine": {"pos": "verb", "m1": "To look at something carefully and closely. Example: The doctor examined the patient.", "m2": "", "ch": "She ___ the fossil under a magnifying glass."},
    "excel": {"pos": "verb", "m1": "To be very good at something. Example: She excels at math and science.", "m2": "", "ch": "Hard work helps you ___ in school."},
    "exclaim": {"pos": "verb", "m1": "To cry out suddenly with strong feeling. Example: 'Look at that!' she exclaimed.", "m2": "", "ch": "'What a beautiful rainbow!' he ___."},
    "expedition": {"pos": "noun", "m1": "A journey organized for a specific purpose. Example: The expedition to the South Pole lasted six months.", "m2": "", "ch": "The scientists went on an ___ to study the rainforest."},
    "explore": {"pos": "verb", "m1": "To travel through an unfamiliar area to learn about it. Example: The astronauts explored the surface of the Moon.", "m2": "", "ch": "We love to ___ the forest behind our house."},
    "expose": {"pos": "verb", "m1": "To make something visible or known. Example: The investigation exposed the truth.", "m2": "", "ch": "Don't ___ the film to direct sunlight."},
    "extraordinary": {"pos": "adjective", "m1": "Very unusual or remarkable. Example: She has an extraordinary talent for painting.", "m2": "", "ch": "The sunset was ___ — the sky turned every shade of orange."},
    "familiar": {"pos": "adjective", "m1": "Well known; easily recognized. Example: The song sounded familiar to me.", "m2": "", "ch": "The neighborhood was ___ because she had lived there as a child."},
    "famine": {"pos": "noun", "m1": "A time when there is very little food and many people go hungry. Example: The famine caused great suffering in the village.", "m2": "", "ch": "The drought led to a terrible ___."},
    "fascinate": {"pos": "verb", "m1": "To attract and hold the attention of someone. Example: The magician fascinated the audience with his tricks.", "m2": "", "ch": "Space travel continues to ___ people of all ages."},
    "fearsome": {"pos": "adjective", "m1": "Causing fear; frightening. Example: The fearsome dragon guarded the treasure.", "m2": "", "ch": "The ___ storm made the animals hide."},
    "feeble": {"pos": "adjective", "m1": "Lacking strength; weak. Example: The feeble old man needed help walking.", "m2": "", "ch": "His ___ attempt to lift the box failed."},
    "fierce": {"pos": "adjective", "m1": "Very strong or violent; intense. Example: The fierce winds knocked down trees.", "m2": "", "ch": "The ___ lion protected its territory."},
    "flexible": {"pos": "adjective", "m1": "Able to bend without breaking. Example: Yoga makes your body more flexible.", "m2": "Willing to change or try new things. Example: She has a flexible schedule.", "ch": "The gymnast was very ___."},
    "focus": {"pos": "verb, noun", "m1": "To concentrate on something. Example: Focus on your work and you'll finish faster.", "m2": "", "ch": "Try to ___ on one task at a time."},
    "force": {"pos": "noun, verb", "m1": "Power or strength. Example: The force of the wind blew the door open.", "m2": "To make someone do something. Example: No one should force you to eat something you don't like.", "ch": "Gravity is the ___ that keeps us on the ground."},
    "fortunate": {"pos": "adjective", "m1": "Lucky; having good fortune. Example: We were fortunate to find seats at the crowded restaurant.", "m2": "", "ch": "She felt ___ to have such supportive friends."},
    "frequent": {"pos": "adjective", "m1": "Happening often. Example: Rain is frequent in the spring.", "m2": "", "ch": "There are ___ buses on this route."},
    "frontier": {"pos": "noun", "m1": "The border of settled land; the edge of the unknown. Example: The pioneers headed west to the frontier.", "m2": "The limit of knowledge. Example: Space is the next frontier for exploration.", "ch": "Scientists are pushing the ___ of medical research."},
    "fury": {"pos": "noun", "m1": "Extreme anger; rage. Example: The fury of the storm frightened everyone.", "m2": "", "ch": "His ___ was clear from the look on his face."},
    "gasp": {"pos": "verb, noun", "m1": "To breathe in quickly because of surprise or shock. Example: She gasped when she saw the surprise party.", "m2": "", "ch": "The audience let out a ___ when the acrobat fell."},
    "generous": {"pos": "adjective", "m1": "Willing to give more than is expected. Example: The generous donor gave money to the school.", "m2": "", "ch": "It was ___ of her to share her lunch."},
    "genuine": {"pos": "adjective", "m1": "Real and true; not fake. Example: This is a genuine diamond, not a fake.", "m2": "Sincere; honest. Example: Her apology was genuine.", "ch": "His smile was ___ and full of warmth."},
    "gigantic": {"pos": "adjective", "m1": "Extremely large; like a giant. Example: The gigantic wave crashed onto the shore.", "m2": "", "ch": "The ___ tree was the tallest in the forest."},
    "glance": {"pos": "verb, noun", "m1": "To look at something quickly. Example: She took a quick glance at her watch.", "m2": "A brief or hurried look. Example: He gave a glance over his shoulder.", "ch": "The detective gave a quick ___ at the clue on the table."},
    "gleam": {"pos": "verb, noun", "m1": "To shine with a soft light. Example: The moonlight gleamed on the lake.", "m2": "", "ch": "The gold coins ___ in the treasure chest."},
    "glisten": {"pos": "verb", "m1": "To sparkle or shine with reflected light. Example: The morning dew glistened on the grass.", "m2": "", "ch": "The snow ___ in the bright sunlight."},
    "gloomy": {"pos": "adjective", "m1": "Dark and sad. Example: The gloomy sky meant rain was coming.", "m2": "Feeling sad or unhappy. Example: He felt gloomy on the rainy day.", "ch": "The ___ basement needed more light."},
    "glory": {"pos": "noun", "m1": "Great honor and praise. Example: The team celebrated their glory after winning the championship.", "m2": "Great beauty. Example: The garden was in its full glory in spring.", "ch": "The soldier was honored for his ___ in battle."},
    "goal": {"pos": "noun", "m1": "Something you are trying to achieve. Example: Her goal is to become a veterinarian.", "m2": "A point scored in sports. Example: He kicked the winning goal.", "ch": "Setting a ___ helps you stay focused."},
    "govern": {"pos": "verb", "m1": "To officially control and lead a country or state. Example: The president governs the nation.", "m2": "", "ch": "Rules ___ how we behave in school."},
    "guarantee": {"pos": "noun, verb", "m1": "A promise that something will happen or work. Example: The store offers a money-back guarantee.", "m2": "", "ch": "I ___ you will love this book."},
    "harsh": {"pos": "adjective", "m1": "Rough, unpleasant, or severe. Example: The harsh winter made travel difficult.", "m2": "Cruel or unkind. Example: His harsh words hurt her feelings.", "ch": "The ___ sunlight made her squint."},
    "heritage": {"pos": "noun", "m1": "Traditions and culture passed down through generations. Example: Our cultural heritage includes stories, music, and food.", "m2": "", "ch": "The festival celebrates our community's rich ___."},
    "hesitate": {"pos": "verb", "m1": "To pause before doing something because of uncertainty. Example: She hesitated before answering the difficult question.", "m2": "", "ch": "Don't ___ — just go for it!"},
    "honor": {"pos": "noun, verb", "m1": "Great respect and admiration. Example: It was an honor to meet the famous author.", "m2": "To show respect. Example: We honor our veterans on Memorial Day.", "ch": "The award was given in ___ of her achievements."},
    "hostile": {"pos": "adjective", "m1": "Unfriendly and aggressive. Example: The hostile crowd shouted at the referee.", "m2": "", "ch": "The ___ environment made survival difficult."},
    "identify": {"pos": "verb", "m1": "To recognize or figure out what something is. Example: Can you identify the bird by its song?", "m2": "", "ch": "The witness was able to ___ the suspect."},
    "illuminate": {"pos": "verb", "m1": "To light up or make bright. Example: Candles illuminated the dark room.", "m2": "To make something clear. Example: The teacher illuminated the difficult concept.", "ch": "The fireworks ___ the night sky."},
    "illustrate": {"pos": "verb", "m1": "To explain something by using pictures or examples. Example: She illustrated her point with a diagram.", "m2": "To draw pictures for a book. Example: The artist illustrated the children's book.", "ch": "Can you ___ your idea with a drawing?"},
    "imagine": {"pos": "verb", "m1": "To form a picture in your mind. Example: Imagine you could fly — where would you go?", "m2": "", "ch": "___ what life was like a hundred years ago."},
    "imitate": {"pos": "verb", "m1": "To copy someone's behavior or actions. Example: The parrot can imitate human speech.", "m2": "", "ch": "The little brother tried to ___ everything his big sister did."},
    "immediate": {"pos": "adjective", "m1": "Happening right now, without delay. Example: The fire required an immediate response.", "m2": "", "ch": "The doctor said she needed ___ attention."},
    "impact": {"pos": "noun, verb", "m1": "A strong effect on someone or something. Example: Pollution has a bad impact on the environment.", "m2": "The force of one thing hitting another. Example: The impact of the crash broke the window.", "ch": "Good teachers have a lasting ___ on their students."},
    "imply": {"pos": "verb", "m1": "To suggest something without saying it directly. Example: Her smile implied that she was happy.", "m2": "", "ch": "His silence seemed to ___ that he agreed."},
    "incredible": {"pos": "adjective", "m1": "Hard to believe; amazing. Example: The magician performed an incredible trick.", "m2": "", "ch": "The view from the mountain top was ___."},
    "independent": {"pos": "adjective", "m1": "Able to do things by yourself without help. Example: She became more independent after learning to cook.", "m2": "", "ch": "An ___ thinker makes decisions on their own."},
    "indicate": {"pos": "verb", "m1": "To point out or show something. Example: The arrow indicated which way to go.", "m2": "", "ch": "The dark clouds ___ that a storm is coming."},
    "influence": {"pos": "noun, verb", "m1": "The power to change how someone thinks or acts. Example: Good friends have a positive influence.", "m2": "", "ch": "Music can ___ your mood."},
    "inhabitant": {"pos": "noun", "m1": "A person or animal that lives in a particular place. Example: The inhabitants of the island welcomed the visitors.", "m2": "", "ch": "The ___ of the town gathered for the festival."},
    "insist": {"pos": "verb", "m1": "To say firmly that something must happen. Example: She insisted on paying for dinner.", "m2": "", "ch": "He ___ that he did not break the vase."},
    "inspire": {"pos": "verb", "m1": "To make someone want to do something great. Example: The speaker inspired the students to follow their dreams.", "m2": "", "ch": "Her courage will ___ others to be brave."},
    "intelligent": {"pos": "adjective", "m1": "Having the ability to learn and understand things quickly. Example: Dolphins are intelligent animals.", "m2": "", "ch": "She is one of the most ___ students in the class."},
    "intent": {"pos": "noun, adjective", "m1": "A plan or purpose. Example: His intent was to help, not to cause trouble.", "m2": "Giving full attention. Example: She was intent on finishing her book.", "ch": "The student was ___ on getting a perfect score."},
    "interpret": {"pos": "verb", "m1": "To explain the meaning of something. Example: How do you interpret this poem?", "m2": "", "ch": "She helped ___ the message written in French."},
    "investigate": {"pos": "verb", "m1": "To look into something carefully to find the truth. Example: The police investigated the robbery.", "m2": "", "ch": "Scientists ___ how diseases spread."},
    "invest": {"pos": "verb", "m1": "To put money or time into something hoping to get more back. Example: She invested time in learning a new language.", "m2": "", "ch": "It's wise to ___ in your education."},
    "journey": {"pos": "noun, verb", "m1": "A long trip from one place to another. Example: The journey from New York to California took five days.", "m2": "", "ch": "The ___ through the mountains was beautiful."},
    "keen": {"pos": "adjective", "m1": "Very interested and eager. Example: She is keen to learn about astronomy.", "m2": "Sharp. Example: The hawk has keen eyesight.", "ch": "He had a ___ interest in ancient history."},
    "knowledge": {"pos": "noun", "m1": "Facts, information, and understanding gained through learning. Example: Books are a great source of knowledge.", "m2": "", "ch": "Her ___ of science impressed everyone."},
    "landscape": {"pos": "noun", "m1": "The visible features of an area of land. Example: The landscape was filled with green hills and rivers.", "m2": "", "ch": "The artist painted a beautiful ___ of the valley."},
    "legend": {"pos": "noun", "m1": "An old story passed down over time that may not be true. Example: The legend of King Arthur has been told for centuries.", "m2": "A famous or important person. Example: She is a legend in the world of music.", "ch": "The ___ says a dragon once lived in the mountain."},
    "liberate": {"pos": "verb", "m1": "To set free. Example: The hero liberated the prisoners from the tower.", "m2": "", "ch": "The army helped ___ the captured city."},
    "locate": {"pos": "verb", "m1": "To find the position of something. Example: Can you locate India on the map?", "m2": "", "ch": "We need to ___ the nearest hospital."},
    "loyal": {"pos": "adjective", "m1": "Always faithful and supportive. Example: A loyal friend stays with you in tough times.", "m2": "", "ch": "The ___ dog waited for its owner every day."},
    "magnificent": {"pos": "adjective", "m1": "Extremely beautiful or impressive. Example: The magnificent palace took your breath away.", "m2": "", "ch": "The sunset over the ocean was ___."},
    "marvel": {"pos": "verb, noun", "m1": "To be filled with wonder. Example: We marveled at the beautiful waterfall.", "m2": "Something amazing. Example: The new bridge is a marvel of engineering.", "ch": "The crowd ___ at the magician's tricks."},
    "massive": {"pos": "adjective", "m1": "Extremely large and heavy. Example: The massive boulder blocked the road.", "m2": "", "ch": "The elephant is a ___ animal."},
    "meek": {"pos": "adjective", "m1": "Quiet, gentle, and not wanting to argue. Example: The meek child never raised her voice.", "m2": "", "ch": "Despite being ___, she had strong beliefs."},
    "method": {"pos": "noun", "m1": "A particular way of doing something. Example: The teacher showed us a new method for solving the problem.", "m2": "", "ch": "What ___ did you use to find the answer?"},
    "mild": {"pos": "adjective", "m1": "Not severe or strong; gentle. Example: We had a mild winter with little snow.", "m2": "", "ch": "The ___ cheese had a soft flavor."},
    "miniature": {"pos": "adjective, noun", "m1": "Very small; a tiny version of something. Example: She collected miniature dolls from around the world.", "m2": "", "ch": "The ___ train set looked just like a real railway."},
    "moral": {"pos": "noun, adjective", "m1": "A lesson about right and wrong from a story. Example: The moral of the story is 'honesty is the best policy.'", "m2": "Related to what is right and wrong. Example: She made the moral choice to return the lost wallet.", "ch": "What is the ___ of this fable?"},
    "navigate": {"pos": "verb", "m1": "To find your way through a place or situation. Example: The captain navigated the ship through the storm.", "m2": "", "ch": "You need a map to ___ through the forest."},
    "negotiate": {"pos": "verb", "m1": "To discuss something to reach an agreement. Example: The two sides negotiated a peace deal.", "m2": "", "ch": "She tried to ___ a later bedtime with her parents."},
    "noble": {"pos": "adjective", "m1": "Having high moral qualities; honorable. Example: It was a noble act to help the stranger.", "m2": "Belonging to royalty. Example: The noble family lived in the castle.", "ch": "Saving the drowning puppy was a ___ deed."},
    "numerous": {"pos": "adjective", "m1": "Very many; a large number. Example: Numerous students signed up for the science club.", "m2": "", "ch": "There were ___ reasons to celebrate."},
    "observe": {"pos": "verb", "m1": "To watch carefully. Example: Scientists observe animals in their natural habitat.", "m2": "To make a comment. Example: She observed that the room was very tidy.", "ch": "The birdwatcher liked to ___ eagles in the wild."},
    "obstacle": {"pos": "noun", "m1": "Something that blocks your way or makes something difficult. Example: The fallen tree was an obstacle on the trail.", "m2": "", "ch": "Lack of money was the biggest ___ to her plans."},
    "obvious": {"pos": "adjective", "m1": "Easy to see or understand; clear. Example: It was obvious that she was tired.", "m2": "", "ch": "The answer was ___ once she read the question again."},
    "occur": {"pos": "verb", "m1": "To happen or take place. Example: The earthquake occurred at 3 AM.", "m2": "To come into your mind. Example: It occurred to me that I forgot my lunch.", "ch": "Accidents can ___ when you're not paying attention."},
    "opportunity": {"pos": "noun", "m1": "A good chance to do something. Example: The scholarship was a great opportunity.", "m2": "", "ch": "Don't miss the ___ to try something new."},
    "ordinary": {"pos": "adjective", "m1": "Normal; not special or different. Example: It seemed like an ordinary day until the surprise happened.", "m2": "", "ch": "She turned an ___ rock into a work of art."},
    "overwhelm": {"pos": "verb", "m1": "To have a very strong effect; to overpower. Example: The amount of homework overwhelmed the student.", "m2": "", "ch": "The cheering crowd seemed to ___ the young singer."},
    "passage": {"pos": "noun", "m1": "A section of a book or piece of writing. Example: Read the passage and answer the questions.", "m2": "A narrow path or corridor. Example: The passage led to a secret room.", "ch": "The ___ in the book described a beautiful garden."},
    "patient": {"pos": "adjective, noun", "m1": "Able to wait calmly without complaining. Example: Be patient — the bus will come soon.", "m2": "A person receiving medical care. Example: The patient waited in the hospital.", "ch": "A good teacher is always ___ with students."},
    "pattern": {"pos": "noun", "m1": "A design that repeats. Example: The wallpaper had a flower pattern.", "m2": "A regular way something happens. Example: She noticed a pattern in the data.", "ch": "The tiles had a beautiful ___ of blue and white."},
    "pause": {"pos": "verb, noun", "m1": "To stop for a short time before continuing. Example: He paused to take a drink of water.", "m2": "", "ch": "She took a ___ before answering the question."},
    "perform": {"pos": "verb", "m1": "To carry out an action or task. Example: The surgeon performed the operation.", "m2": "To entertain an audience. Example: The band performed at the school concert.", "ch": "The actors ___ in front of a large audience."},
    "persuade": {"pos": "verb", "m1": "To convince someone to do or believe something. Example: She persuaded her brother to help with the chores.", "m2": "", "ch": "Can you ___ your friend to join the team?"},
    "pierce": {"pos": "verb", "m1": "To make a hole through something. Example: The needle pierced the fabric.", "m2": "", "ch": "The thorn ___ through her shoe."},
    "plunge": {"pos": "verb, noun", "m1": "To jump or dive quickly into something. Example: She plunged into the cold swimming pool.", "m2": "", "ch": "The temperature ___ below freezing overnight."},
    "popular": {"pos": "adjective", "m1": "Liked by many people. Example: Pizza is a popular food among kids.", "m2": "", "ch": "The ___ book was checked out by everyone in class."},
    "precious": {"pos": "adjective", "m1": "Very valuable or dear to someone. Example: The necklace was made of precious stones.", "m2": "", "ch": "Time is the most ___ gift you can give someone."},
    "predict": {"pos": "verb", "m1": "To say what you think will happen in the future. Example: Scientists predict that it will rain tomorrow.", "m2": "", "ch": "Can you ___ what will happen next in the story?"},
    "preserve": {"pos": "verb", "m1": "To keep something safe or in good condition. Example: We need to preserve the rainforest.", "m2": "", "ch": "The museum works to ___ ancient artifacts."},
    "previous": {"pos": "adjective", "m1": "Happening before something else. Example: In the previous chapter, the hero escaped from the cave.", "m2": "", "ch": "Her ___ school was in a different state."},
    "principle": {"pos": "noun", "m1": "A basic truth or belief that guides behavior. Example: Honesty is an important principle.", "m2": "", "ch": "She lived by the ___ that kindness matters most."},
    "prompt": {"pos": "adjective, verb", "m1": "Done quickly without delay. Example: Thank you for your prompt reply.", "m2": "To cause someone to do something. Example: The question prompted a lively discussion.", "ch": "Please be ___ — arrive on time for class."},
    "prosper": {"pos": "verb", "m1": "To be successful and grow strong. Example: The business prospered and opened new stores.", "m2": "", "ch": "With hard work, the farm began to ___."},
    "rare": {"pos": "adjective", "m1": "Not found or seen very often; uncommon. Example: That is a rare type of butterfly.", "m2": "", "ch": "Finding a four-leaf clover is very ___."},
    "refuse": {"pos": "verb", "m1": "To say no to something. Example: She refused to give up, even when things got hard.", "m2": "", "ch": "He ___ to eat his vegetables."},
    "reliable": {"pos": "adjective", "m1": "Trustworthy; can be depended on. Example: She is a reliable friend who always keeps her promises.", "m2": "", "ch": "A ___ car starts every time you turn the key."},
    "reluctant": {"pos": "adjective", "m1": "Not willing to do something; hesitant. Example: The reluctant student slowly raised his hand.", "m2": "", "ch": "She was ___ to try the spicy food."},
    "remote": {"pos": "adjective", "m1": "Far away from other places. Example: The village was in a remote area of the mountains.", "m2": "", "ch": "The ___ island had no roads or electricity."},
    "resemble": {"pos": "verb", "m1": "To look like or be similar to someone or something. Example: The daughter resembles her mother.", "m2": "", "ch": "The cloud ___ a rabbit."},
    "resolve": {"pos": "verb, noun", "m1": "To find a solution to a problem. Example: They resolved the argument peacefully.", "m2": "Firm determination. Example: She had the resolve to finish the marathon.", "ch": "We must ___ this problem before it gets worse."},
    "resource": {"pos": "noun", "m1": "Something useful that can be used when needed. Example: Water is an important natural resource.", "m2": "", "ch": "The library is a great ___ for research."},
    "reveal": {"pos": "verb", "m1": "To make something known that was hidden or secret. Example: The magician refused to reveal his tricks.", "m2": "", "ch": "The letter will ___ the truth about what happened."},
    "revive": {"pos": "verb", "m1": "To bring back to life or make active again. Example: A glass of cold water revived her after the run.", "m2": "", "ch": "Rain helped ___ the dying plants."},
    "ripple": {"pos": "noun, verb", "m1": "A small wave on the surface of water. Example: A stone thrown into the pond made ripples.", "m2": "", "ch": "The breeze caused a ___ across the lake."},
    "route": {"pos": "noun", "m1": "A way or path from one place to another. Example: We took the fastest route to the airport.", "m2": "", "ch": "What ___ should we take to avoid traffic?"},
    "ruin": {"pos": "verb, noun", "m1": "To destroy or damage badly. Example: The flood ruined the crops.", "m2": "The remains of a destroyed building. Example: The ancient ruins attracted many tourists.", "ch": "Don't let one mistake ___ your whole day."},
    "rural": {"pos": "adjective", "m1": "Relating to the countryside, not the city. Example: They moved from the city to a rural farm.", "m2": "", "ch": "Life in ___ areas is quieter than in cities."},
    "sacred": {"pos": "adjective", "m1": "Holy or connected to God or religion. Example: The temple is a sacred place.", "m2": "", "ch": "The ancient tree was considered ___ by the villagers."},
    "scarce": {"pos": "adjective", "m1": "Not enough; hard to find. Example: Clean water is scarce in some parts of the world.", "m2": "", "ch": "Food became ___ during the drought."},
    "schedule": {"pos": "noun, verb", "m1": "A plan that lists times for activities or events. Example: My school schedule starts at 8 AM.", "m2": "To plan or arrange for something to happen at a certain time. Example: We scheduled the meeting for Friday.", "ch": "Write a sentence about your weekly ___."},
    "sensitive": {"pos": "adjective", "m1": "Easily affected by things; aware of others' feelings. Example: She is sensitive to loud noises.", "m2": "", "ch": "He is a ___ person who cares about others."},
    "shatter": {"pos": "verb", "m1": "To break suddenly into many small pieces. Example: The ball shattered the glass window.", "m2": "To destroy completely. Example: The bad news shattered her hopes.", "ch": "The dropped vase ___ into a hundred tiny pieces."},
    "shallow": {"pos": "adjective", "m1": "Not deep. Example: The shallow pool was safe for young children.", "m2": "", "ch": "The ___ end of the pool is only two feet deep."},
    "shelter": {"pos": "noun, verb", "m1": "A place that protects you from weather or danger. Example: They found shelter from the rain under a tree.", "m2": "", "ch": "The family built a ___ to stay safe during the storm."},
    "signal": {"pos": "noun, verb", "m1": "A sign or action that sends a message. Example: The green light is a signal to go.", "m2": "", "ch": "She waved her hand as a ___ to stop."},
    "significant": {"pos": "adjective", "m1": "Important or large enough to have an effect. Example: The discovery was a significant moment in science.", "m2": "", "ch": "Exercise has a ___ impact on your health."},
    "soar": {"pos": "verb", "m1": "To fly high in the air. Example: The eagle soared above the mountains.", "m2": "", "ch": "The kite ___ high in the windy sky."},
    "solid": {"pos": "adjective", "m1": "Hard and firm; not liquid or gas. Example: Ice is the solid form of water.", "m2": "Strong and reliable. Example: She built a solid friendship.", "ch": "The bridge is made of ___ stone."},
    "source": {"pos": "noun", "m1": "Where something comes from. Example: The river's source is high in the mountains.", "m2": "", "ch": "What is the ___ of this information?"},
    "splendid": {"pos": "adjective", "m1": "Very impressive and beautiful. Example: The splendid fireworks lit up the sky.", "m2": "", "ch": "The palace had a ___ view of the gardens."},
    "storm": {"pos": "noun, verb", "m1": "Violent weather with strong winds, rain, thunder, or snow. Example: The storm knocked down several trees.", "m2": "To move angrily or forcefully. Example: She stormed out of the room.", "ch": "Write a sentence describing a ___ you have experienced."},
    "strategy": {"pos": "noun", "m1": "A careful plan to achieve a goal. Example: The team discussed their strategy before the game.", "m2": "", "ch": "What ___ will you use to study for the test?"},
    "struggle": {"pos": "verb, noun", "m1": "To try very hard to do something difficult. Example: She struggled to carry the heavy box.", "m2": "A difficult fight or effort. Example: The struggle for freedom lasted many years.", "ch": "Don't give up when you ___ with a hard problem."},
    "succeed": {"pos": "verb", "m1": "To achieve what you set out to do. Example: If you work hard, you will succeed.", "m2": "", "ch": "She studied every night and ___ on the test."},
    "sufficient": {"pos": "adjective", "m1": "Enough; as much as needed. Example: Do you have sufficient supplies for the trip?", "m2": "", "ch": "Make sure you have ___ sleep before the exam."},
    "summit": {"pos": "noun", "m1": "The highest point of a mountain. Example: They reached the summit after climbing for six hours.", "m2": "An important meeting of leaders. Example: World leaders gathered for the summit.", "ch": "The climbers planted a flag at the ___."},
    "superb": {"pos": "adjective", "m1": "Excellent; of the highest quality. Example: The chef prepared a superb meal.", "m2": "", "ch": "The dancer gave a ___ performance that amazed the audience."},
    "survive": {"pos": "verb", "m1": "To continue to live through a difficult situation. Example: The plants survived the harsh winter.", "m2": "", "ch": "How do animals ___ in the desert?"},
    "swift": {"pos": "adjective", "m1": "Moving very fast. Example: The swift cheetah caught its prey.", "m2": "", "ch": "The river had a ___ current after the rain."},
    "symbol": {"pos": "noun", "m1": "Something that represents or stands for something else. Example: The dove is a symbol of peace.", "m2": "", "ch": "The heart is a ___ of love."},
    "talent": {"pos": "noun", "m1": "A natural ability to do something well. Example: She has a talent for drawing.", "m2": "", "ch": "Everyone has a special ___."},
    "territory": {"pos": "noun", "m1": "An area of land. Example: The wolf defended its territory.", "m2": "", "ch": "The explorers mapped the new ___."},
    "timid": {"pos": "adjective", "m1": "Shy and lacking confidence. Example: The timid rabbit hid in its burrow.", "m2": "", "ch": "The ___ child was afraid to speak in front of the class."},
    "tradition": {"pos": "noun", "m1": "A custom or belief passed down through generations. Example: Decorating the tree is a holiday tradition.", "m2": "", "ch": "Our family ___ is to eat dinner together every Sunday."},
    "trait": {"pos": "noun", "m1": "A quality or characteristic of a person. Example: Honesty is an important character trait.", "m2": "", "ch": "Bravery is a ___ of a good leader."},
    "treasure": {"pos": "noun, verb", "m1": "Very valuable things, like gold or jewels. Example: The pirates buried their treasure on the island.", "m2": "To value something greatly. Example: She treasured the necklace from her grandmother.", "ch": "The old map showed where the ___ was hidden."},
    "tremendous": {"pos": "adjective", "m1": "Very large, great, or powerful. Example: The crowd gave a tremendous cheer.", "m2": "", "ch": "She put in a ___ amount of effort."},
    "triumph": {"pos": "noun, verb", "m1": "A great victory or achievement. Example: Winning the championship was a triumph for the team.", "m2": "", "ch": "After months of practice, her concert was a ___."},
    "unique": {"pos": "adjective", "m1": "One of a kind; unlike anything else. Example: Every person's fingerprint is unique.", "m2": "", "ch": "The artist created a truly ___ sculpture."},
    "unite": {"pos": "verb", "m1": "To join together as one. Example: The community united to help after the flood.", "m2": "", "ch": "Let's ___ to solve this problem together."},
    "urban": {"pos": "adjective", "m1": "Relating to a city. Example: Urban areas have more traffic than rural ones.", "m2": "", "ch": "The ___ park was a green oasis in the busy city."},
    "value": {"pos": "noun, verb", "m1": "How much something is worth. Example: The value of the old painting increased over time.", "m2": "To consider something important. Example: I value our friendship.", "ch": "We should ___ the things we have."},
    "variety": {"pos": "noun", "m1": "A number of different kinds. Example: The store sells a variety of fruits.", "m2": "", "ch": "There is a wide ___ of books in the library."},
    "vary": {"pos": "verb", "m1": "To be different or to change. Example: Temperatures vary from day to day.", "m2": "", "ch": "Opinions ___ on which movie is the best."},
    "vast": {"pos": "adjective", "m1": "Very large in area or amount. Example: The vast desert stretched for miles.", "m2": "", "ch": "The ocean is a ___ body of water."},
    "veteran": {"pos": "noun", "m1": "Someone with a lot of experience, or a former member of the military. Example: The veteran soldier shared his stories.", "m2": "", "ch": "On Veterans Day, we honor every ___ who served our country."},
    "vibrant": {"pos": "adjective", "m1": "Full of energy and life; bright and colorful. Example: The vibrant flowers brightened the garden.", "m2": "", "ch": "The market was ___ with colors and sounds."},
    "vivid": {"pos": "adjective", "m1": "Producing strong, clear images in the mind; very bright. Example: She had a vivid imagination.", "m2": "", "ch": "The ___ sunset turned the sky red and orange."},
    "volunteer": {"pos": "noun, verb", "m1": "A person who does work without being paid. Example: The volunteer helped serve food at the shelter.", "m2": "", "ch": "She decided to ___ at the animal rescue center."},
    "voyage": {"pos": "noun", "m1": "A long journey, especially by sea or through space. Example: The voyage across the Atlantic took two weeks.", "m2": "", "ch": "The ship set sail on a ___ around the world."},
    "wander": {"pos": "verb", "m1": "To walk around without a clear direction. Example: We wandered through the old town exploring the streets.", "m2": "", "ch": "Don't ___ too far from the campsite."},
    "watchful": {"pos": "adjective", "m1": "Carefully observing everything; alert. Example: The watchful mother kept an eye on her children.", "m2": "", "ch": "Stay ___ when walking through the woods."},
    "wilderness": {"pos": "noun", "m1": "A wild, natural area where no people live. Example: They camped in the wilderness far from any town.", "m2": "", "ch": "The national park protects thousands of acres of ___."},
    "wisdom": {"pos": "noun", "m1": "The ability to make good decisions based on knowledge and experience. Example: Grandma shared her wisdom with the family.", "m2": "", "ch": "The old teacher was known for her great ___."},
    "wit": {"pos": "noun", "m1": "The ability to say clever and funny things. Example: Her quick wit made everyone laugh.", "m2": "", "ch": "His sharp ___ kept the audience entertained."},
    "wreckage": {"pos": "noun", "m1": "The broken pieces of something that has been destroyed. Example: The wreckage of the plane was found in the ocean.", "m2": "", "ch": "Rescue workers searched through the ___ for survivors."},
}

# ============================================================
# Now update all content files with proper definitions
# ============================================================

for grade in [3, 4, 5]:
    content_dir = f"/Users/suchitrasharma/vocab-agent/content/grade{grade}"
    files = sorted(os.listdir(content_dir))

    updated = 0
    total_defined = 0
    placeholder_count = 0

    for fname in files:
        fpath = os.path.join(content_dir, fname)
        with open(fpath) as f:
            data = json.load(f)

        changed = False
        for defn in data["definitions"]:
            word = defn["word"]
            if word in DEFS:
                d = DEFS[word]
                defn["partOfSpeech"] = d["pos"]
                defn["meaning1"] = d["m1"]
                defn["meaning2"] = d.get("m2", "")
                defn["studentChallenge"] = d["ch"]
                total_defined += 1
                changed = True
            else:
                placeholder_count += 1

        if changed:
            with open(fpath, "w") as f:
                json.dump(data, f, indent=2)
            updated += 1

    print(f"Grade {grade}: Updated {updated} files, {total_defined} words defined, {placeholder_count} still placeholder")

print("\nDone!")
